### ISSUE TITLE
Get lifetime total deposits in USD api endpoint

### ISSUE THREAD

**Issue by jenlij** [storj/storjscan#10]
For each deposit address, we want to see total amount of lifetime deposits.

**Comment by jenlij** [comment]
For a given payment account, return lifetime total USD deposits for transactions with greater than x confirmations.

**Comment by jenlij** [comment]
We want to be able to quickly display the users total deposits/claims/balance on the satellite dashboard. Whether that is done via API call to storjscan for total deposits, or by keeping track in the satellitedb https://github.com/storj/storjscan/issues/29 is up to the team.

**Comment by shaupt131** [comment]
For right now we will query Storjscan for the total balance, but at some point we will start to store these transaction details in the satellite.  Closing this ticket and we will create a more appropriate ticket once we better understand.
