### ISSUE TITLE
Create storj-up based docker-compose environment for storjscan

### ISSUE THREAD

**Issue by jenlij** [storj/storjscan#37]
We need to add the ability to spin up an instance of storjscan with storj-up. This will allow us to easily test changes between the satellite and storjscan. it also allows us to test the queries between the satellite and storjscan. 

Acceptance Criteria: 
- Add Ethereum node to the docker-compose file for storj-up
- Add storjScan to storj-up

**Comment by elek** [comment]
I was thinking about this and I propose to do this in two phases as storjscan still in early phase and flags are changing:

 1. As a first step, we can commit a docker-compose file to the storjscan which is generated with storj-up and includes geth + storjscan (with local bind-mounted binary).
 2. After first release (or ready-to-test candidate) we can copy the compose file to storjscan. (It also requires creating storjscan docker images...)

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storjscan/+/7245
