### ISSUE TITLE
Add REST API which returns with all deposits of one Satellite

### ISSUE THREAD

**Issue by elek** [storj/storjscan#39]
To periodically update the deposit for each claimed wallet on satellite side we need a generic api which returns all the new deposits:

* Input: satellite identity (the key of the authentication) 
* from (block id): the oldest block until we check the history from the (almost) latest one (almost latest = confirmed = head - (2..3)

returns all the deposits to any of the wallets which are claimed by the satellite

**Comment by jenlij** [comment]
- The satellite will call this API in a chore (https://github.com/storj/storjscan/issues/29)
- Start with the block number right before the time of first deployment? Or scan over whole blockchain?
- get all wallets associated with the satellite. (optimization: group these by max number that we can send to check logs)
- check new logs after the last block we checked and filter by wallets found above
- Return the list of logs to the satellite

- @jenlij add satellite identifier and CLI identifier to wallets table
