### ISSUE TITLE
Add USD value at time of token deposit to Get Transactions API endpoint

### ISSUE THREAD

**Issue by jenlij** [storj/storjscan#4]

**Comment by dlamarmorgan** [comment]
- Collect and store STORJ token price history (regular intervals, once a minute)
- Deposits are calculated as USD deposits using the STORJ token price at the time of the deposit
- This service has no state other than the blockchain and a history of STORJ token USD value. We do expect to store all STORJ token price history from the time of deployment going forward with this design
