### ISSUE TITLE
Add USD value to payments (add field to type and populate in the API)

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storjscan#46]
Currently, we only have token value on payment type.  We also want to return USD value.  We have DB and chore that returns historic prices for Storj token.  We want to add logic to service methods that populate the USD value of the payment.  

Acceptance Criteria:
If price isn't available, return an error (failure)

**Comment by rikysya** [comment]
https://review.dev.storj.io/c/storj/storjscan/+/7642
