### ISSUE TITLE
Add a cleanup chore for token price history DB

### ISSUE THREAD

**Issue by shaupt131** [storj/storjscan#48]
Right now, the database stores a token price history every 60 seconds.  Eventually, this is going to lead to a lot of data to store.  We need to implement some kind of cleanup chore to keep the database a reasonable size.  

Acceptance criteria:  

- Run a cleanup job every month for data that is > 30 days old
- Token price and blockheader

**Comment by jenlij** [comment]
not a blocker for storjscan deployment
