### ISSUE TITLE
Add support for CRDB on storj scan

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storjscan#53]
Currently, Storjscan does not support CRDB. in order to minimize our operational overhead, we want to run the DB for Storjscan on CRDB instead of postgres. 

- We need to change the generation scripts https://github.com/storj/storjscan/blob/main/storjscandb/dbx/gen.sh
- Add the DBX generation flag for CRDB in storj scan https://github.com/storj/storjscan/blob/main/storjscandb/dbx/gen.sh
- And add some files that are missing for CRDB on storjscan (Satellite example: https://github.com/storj/storj/blob/main/satellite/satellitedb/dbx/cockroach.go)
- We need to add a CRDB initial migration (satellite example https://github.com/storj/storj/blob/main/satellite/satellitedb/migrate.go)

Acceptance Criteria
- do all the things and stuff listed above

**Comment by jenlij** [comment]
https://review.dev.storj.io/c/storj/storjscan/+/8125
