### ISSUE TITLE
Ensure multiple storage scan instances can be ran per satellite

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storjscan#54]
Check the concurrency of the StorjScan service

Running multiple instances of Storjscan will
- create more API calls to outside services (token price provider & node provider)
- It may create some contention on updates to the DB (at least on token price)

Acceptance Criteria: 
- Test to see if this works with Storj-up

**Comment by iglesiasbrandon** [comment]
@ethanadams @kristaxox what are you using to load balance when scaling services?

**Comment by ethanadams** [comment]
> @ethanadams @kristaxox what are you using to load balance when scaling services?

There are currently 2 storjscan pods in QA behind a kubernetes internal load balancer, with no session affinity
Current IP/port is `10.112.0.45:10000`

**Comment by iglesiasbrandon** [comment]
That's perfect, thanks for letting us know @ethanadams we are going to close this ticket.
