### ISSUE TITLE
Create health endpoint on Storj Scan

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storjscan#55]
StorjScan needs a health endpoint so that we can monitor it more easily and create alerts if it goes down. 
Please reference the endpoint on the gateway-mt or Auth service as an example: 
- https://github.com/storj/gateway-mt/blob/60e570a8e083d5cfe715fdef30b1d4031063a800/pkg/authclient/authclient.go#L149
- https://github.com/storj/gateway-mt/blob/52c852480d6d7348bea23c470b7f7a90b0ddac0c/pkg/server/server.go#L140

Acceptance Criteria: 
- A health endpoint as been added that our infra team can utilize.

**Comment by jenlij** [comment]
https://review.dev.storj.io/c/storj/storjscan/+/8153

**Comment by jenlij** [comment]
Took a little longer due to changing the design and also testing with storj-up
