### ISSUE TITLE
Storjscan test: Verify that STORJ payments that occur while the invoices are being generated behave as expected

### ISSUE THREAD

**Issue by jenlij** [storj/storjscan#60]
Eg we want to avoid double-counting payments, taking credit for pending payments, adding invoice items for pending invoice items

**Comment by jenlij** [comment]
Automated test with Storj-up. Add usage, generate invoice, send a token deposit between invoice generation and finalization.
Waiting on invoice generation changes.

**Comment by iglesiasbrandon** [comment]
PR for this change is: https://review.dev.storj.io/c/storj/up/+/8505
