### ISSUE TITLE
Storjscan test: blockchain reorg integration test

### ISSUE THREAD

**Issue by jenlij** [storj/storjscan#64]
When a blockchain reorg happens, we need to make sure no-longer valid payments are in the satellitedb.

**Comment by dlamarmorgan** [comment]
Recommended approach.
Save off two versions of the chain state that have some number of initial transactions that are the same, but the last few are different. We should then be able to start the geth node with one of the two chain states, let the transactions propagate through the system, then restart the node with the second chain state to "trick" storjscan into thinking it was a reorg.

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/up/+/8469
