### ISSUE TITLE
Investigate why storj scan is ignoring the 2 minute get price interval set in the config

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storjscan#70]
When deploying storjscan we noticed it was getting price info every minute instead of every two minutes as specified in the config. investigate why its not respecting the config value and fix it.

**Comment by dlamarmorgan** [comment]
The interval is working as expected. There are multiple instances of storjscan running that are all requesting the token price data, which results in token price DB entries that are more frequent than the request interval.
