### ISSUE TITLE
Remove events chore from storjscan

### ISSUE THREAD

**Issue by dlamarmorgan** [storj/storjscan#86]
The events chore added to storjscan leads to more requests to the infura API because we run multiple instances of the storjscan API. Instead use the satellite requests that come from the satellite core chore, which has only 1 instance, and rate limit these requests so they don't all query the infura node.

**Comment by shaupt131** [comment]
Working on getting tests to pass before pushing for review.  

Rate limiting is still affecting transactions hitting US1 promptly.

stretch goal to have this ready for review by tomorrow, either split on unsplit.

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/storjscan/+/13969
https://review.dev.storj.io/c/storj/storjscan/+/13970
https://review.dev.storj.io/c/storj/storjscan/+/13971

**Comment by shaupt131** [comment]
Pushed for review.  

Jen and Ivan will review.

**Comment by shaupt131** [comment]
Fully merged.  Cut a storjscan release branch yesterday and will be deployed to QA today.  Damein will be checking the base functionality and checking infra statistics to see if the number of transactions decreases.

**Comment by shaupt131** [comment]
This was deployed to QA and results were mixed.  Investigating how to continue to improve.  Pushed a new change for review.  

#### Next steps:  
Ivan to review https://review.dev.storj.io/c/storj/storjscan/+/14029

**Comment by dlamarmorgan** [comment]
Need a few more reviews
https://review.dev.storj.io/c/storj/storjscan/+/14040
https://review.dev.storj.io/c/storj/storjscan/+/14043
https://review.dev.storj.io/c/storj/storjscan/+/14051

**Comment by shaupt131** [comment]
Will be deploying to QA soon.  Will need to perform quality checks before we deploy to other satellites, as well as wait for billing to finish.

**Comment by shaupt131** [comment]
Has been tested by Damein and Andrii.  Found to be reducing the number of requests by quite a bit, so things are looking good!  Billing has completed, so Damein push the latest storjscan to all satellites.
